scrape_configs:
  - job_name: 'mysql_exporter_test001'
    scrape_timeout: 10s
    scrape_interval: 1m
    static_configs:
      - targets:
          - '10.0.44.68:9104'
        labels:
          name: test001
          __metrics_path__: /metrics
          __param_name: test001

  - job_name: 'mysql_exporter_test002'
    scrape_timeout: 10s
    scrape_interval: 1m
    static_configs:
      - targets:
          - '10.0.44.68:9104'
        labels:
          name: test002
          __metrics_path__: /metrics
          __param_name: test002